"""create native clinical schema

Revision ID: 48b3bb684508
Revises:
Create Date: 2026-09-06 18:59:15.140801

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48b3bb684508"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinical_provenance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("source_system", sa.String(length=100), nullable=True),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("authored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("author_id", sa.String(length=100), nullable=True),
        sa.Column("recorder_id", sa.String(length=100), nullable=True),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_type", "resource_id", "version", name="uq_provenance_version"
        ),
    )
    op.create_index(
        op.f("ix_clinical_provenance_resource_id"),
        "clinical_provenance",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_provenance_resource_type"),
        "clinical_provenance",
        ["resource_type"],
        unique=False,
    )
    op.create_table(
        "patient",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("medical_record_number", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(length=20), nullable=False),
        sa.Column("contact_info", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("emergency_contact", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_medical_record_number"), "patient", ["medical_record_number"], unique=True
    )
    op.create_table(
        "resource_relationship",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_resource_type", sa.String(length=50), nullable=False),
        sa.Column("source_resource_id", sa.Uuid(), nullable=False),
        sa.Column("target_resource_type", sa.String(length=50), nullable=False),
        sa.Column("target_resource_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_resource_type",
            "source_resource_id",
            "target_resource_type",
            "target_resource_id",
            "relationship_type",
            name="uq_resource_relationship",
        ),
    )
    op.create_index(
        op.f("ix_resource_relationship_relationship_type"),
        "resource_relationship",
        ["relationship_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_relationship_source_resource_id"),
        "resource_relationship",
        ["source_resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_relationship_source_resource_type"),
        "resource_relationship",
        ["source_resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_relationship_target_resource_id"),
        "resource_relationship",
        ["target_resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resource_relationship_target_resource_type"),
        "resource_relationship",
        ["target_resource_type"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "encounter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_type", sa.String(length=30), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("clinician_id", sa.String(length=100), nullable=True),
        sa.Column("clinician_name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("audio_metadata", sa.JSON(), nullable=True),
        sa.Column("structured_summary", sa.JSON(), nullable=True),
        sa.Column("chief_complaint", sa.Text(), nullable=True),
        sa.Column("clinical_assessment", sa.Text(), nullable=True),
        sa.Column("treatment_plan", sa.Text(), nullable=True),
        sa.Column("is_compliant", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("updated_by", sa.String(length=100), nullable=True),
        sa.Column("prior_encounter_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at", name="ck_encounter_time_range"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prior_encounter_id"], ["encounter.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encounter_patient_id"), "encounter", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_encounter_prior_encounter_id"), "encounter", ["prior_encounter_id"], unique=False
    )
    op.create_index(op.f("ix_encounter_status"), "encounter", ["status"], unique=False)
    op.create_table(
        "chart_review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("input_snapshot", sa.JSON(), nullable=False),
        sa.Column("output_json", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.String(length=10), nullable=True),
        sa.Column("review_flags", sa.JSON(), nullable=True),
        sa.Column("provider_name", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["encounter_id"], ["encounter.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chart_review_encounter_id"), "chart_review", ["encounter_id"], unique=False
    )
    op.create_index(
        op.f("ix_chart_review_patient_id"), "chart_review", ["patient_id"], unique=False
    )
    op.create_index(op.f("ix_chart_review_status"), "chart_review", ["status"], unique=False)
    op.create_table(
        "clinical_document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("authored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["encounter_id"], ["encounter.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_document_category"), "clinical_document", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_document_encounter_id"),
        "clinical_document",
        ["encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_document_patient_id"), "clinical_document", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_document_status"), "clinical_document", ["status"], unique=False
    )
    op.create_table(
        "diagnostic_report",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("originating_encounter_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("conclusion", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["originating_encounter_id"], ["encounter.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_diagnostic_report_originating_encounter_id"),
        "diagnostic_report",
        ["originating_encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_report_patient_id"), "diagnostic_report", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_diagnostic_report_status"), "diagnostic_report", ["status"], unique=False
    )
    op.create_table(
        "encounter_narrative",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["encounter_id"], ["encounter.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_encounter_narrative_encounter_id"),
        "encounter_narrative",
        ["encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_encounter_narrative_patient_id"),
        "encounter_narrative",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "immunization",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("originating_encounter_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("vaccine_code", sa.String(length=100), nullable=False),
        sa.Column("vaccine_display", sa.String(length=200), nullable=False),
        sa.Column("administered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("manufacturer", sa.String(length=200), nullable=True),
        sa.Column("lot_number", sa.String(length=100), nullable=True),
        sa.Column("performer_name", sa.String(length=200), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["originating_encounter_id"], ["encounter.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_immunization_originating_encounter_id"),
        "immunization",
        ["originating_encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_immunization_patient_id"), "immunization", ["patient_id"], unique=False
    )
    op.create_index(op.f("ix_immunization_status"), "immunization", ["status"], unique=False)
    op.create_table(
        "medication",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("originating_encounter_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("medication_code", sa.String(length=100), nullable=False),
        sa.Column("medication_display", sa.String(length=200), nullable=False),
        sa.Column("dosage_text", sa.Text(), nullable=True),
        sa.Column("prescribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at",
            name="ck_medication_time_range",
        ),
        sa.ForeignKeyConstraint(
            ["originating_encounter_id"], ["encounter.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_originating_encounter_id"),
        "medication",
        ["originating_encounter_id"],
        unique=False,
    )
    op.create_index(op.f("ix_medication_patient_id"), "medication", ["patient_id"], unique=False)
    op.create_index(op.f("ix_medication_status"), "medication", ["status"], unique=False)
    op.create_table(
        "procedure",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("originating_encounter_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("display", sa.String(length=200), nullable=False),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("performer_name", sa.String(length=200), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["originating_encounter_id"], ["encounter.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_procedure_originating_encounter_id"),
        "procedure",
        ["originating_encounter_id"],
        unique=False,
    )
    op.create_index(op.f("ix_procedure_patient_id"), "procedure", ["patient_id"], unique=False)
    op.create_index(op.f("ix_procedure_status"), "procedure", ["status"], unique=False)
    op.create_table(
        "attachment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("clinical_document_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinical_document_id"], ["clinical_document.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_attachment_clinical_document_id"),
        "attachment",
        ["clinical_document_id"],
        unique=False,
    )
    op.create_table(
        "chart_review_citation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chart_review_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["chart_review_id"], ["chart_review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chart_review_citation_chart_review_id"),
        "chart_review_citation",
        ["chart_review_id"],
        unique=False,
    )
    op.create_table(
        "chart_review_source_ref",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chart_review_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(["chart_review_id"], ["chart_review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chart_review_source_ref_chart_review_id"),
        "chart_review_source_ref",
        ["chart_review_id"],
        unique=False,
    )
    op.create_table(
        "imaging_study",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("originating_encounter_id", sa.Uuid(), nullable=True),
        sa.Column("clinical_document_id", sa.Uuid(), nullable=True),
        sa.Column("diagnostic_report_id", sa.Uuid(), nullable=True),
        sa.Column("modality", sa.String(length=30), nullable=False),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("external_study_id", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinical_document_id"], ["clinical_document.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["diagnostic_report_id"], ["diagnostic_report.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["originating_encounter_id"], ["encounter.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_imaging_study_clinical_document_id"),
        "imaging_study",
        ["clinical_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_imaging_study_diagnostic_report_id"),
        "imaging_study",
        ["diagnostic_report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_imaging_study_originating_encounter_id"),
        "imaging_study",
        ["originating_encounter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_imaging_study_patient_id"), "imaging_study", ["patient_id"], unique=False
    )
    op.create_table(
        "observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("diagnostic_report_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("display", sa.String(length=200), nullable=False),
        sa.Column("value_type", sa.String(length=30), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=100), nullable=True),
        sa.Column("data_absent_reason", sa.String(length=500), nullable=True),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(value IS NULL) != (data_absent_reason IS NULL)",
            name="ck_observation_value_or_absence_reason",
        ),
        sa.ForeignKeyConstraint(
            ["diagnostic_report_id"], ["diagnostic_report.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patient.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observation_diagnostic_report_id"),
        "observation",
        ["diagnostic_report_id"],
        unique=False,
    )
    op.create_index(op.f("ix_observation_patient_id"), "observation", ["patient_id"], unique=False)
    op.create_index(op.f("ix_observation_status"), "observation", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observation_status"), table_name="observation")
    op.drop_index(op.f("ix_observation_patient_id"), table_name="observation")
    op.drop_index(op.f("ix_observation_diagnostic_report_id"), table_name="observation")
    op.drop_table("observation")
    op.drop_index(op.f("ix_imaging_study_patient_id"), table_name="imaging_study")
    op.drop_index(op.f("ix_imaging_study_originating_encounter_id"), table_name="imaging_study")
    op.drop_index(op.f("ix_imaging_study_diagnostic_report_id"), table_name="imaging_study")
    op.drop_index(op.f("ix_imaging_study_clinical_document_id"), table_name="imaging_study")
    op.drop_table("imaging_study")
    op.drop_index(
        op.f("ix_chart_review_source_ref_chart_review_id"), table_name="chart_review_source_ref"
    )
    op.drop_table("chart_review_source_ref")
    op.drop_index(
        op.f("ix_chart_review_citation_chart_review_id"), table_name="chart_review_citation"
    )
    op.drop_table("chart_review_citation")
    op.drop_index(op.f("ix_attachment_clinical_document_id"), table_name="attachment")
    op.drop_table("attachment")
    op.drop_index(op.f("ix_procedure_status"), table_name="procedure")
    op.drop_index(op.f("ix_procedure_patient_id"), table_name="procedure")
    op.drop_index(op.f("ix_procedure_originating_encounter_id"), table_name="procedure")
    op.drop_table("procedure")
    op.drop_index(op.f("ix_medication_status"), table_name="medication")
    op.drop_index(op.f("ix_medication_patient_id"), table_name="medication")
    op.drop_index(op.f("ix_medication_originating_encounter_id"), table_name="medication")
    op.drop_table("medication")
    op.drop_index(op.f("ix_immunization_status"), table_name="immunization")
    op.drop_index(op.f("ix_immunization_patient_id"), table_name="immunization")
    op.drop_index(op.f("ix_immunization_originating_encounter_id"), table_name="immunization")
    op.drop_table("immunization")
    op.drop_index(op.f("ix_encounter_narrative_patient_id"), table_name="encounter_narrative")
    op.drop_index(op.f("ix_encounter_narrative_encounter_id"), table_name="encounter_narrative")
    op.drop_table("encounter_narrative")
    op.drop_index(op.f("ix_diagnostic_report_status"), table_name="diagnostic_report")
    op.drop_index(op.f("ix_diagnostic_report_patient_id"), table_name="diagnostic_report")
    op.drop_index(
        op.f("ix_diagnostic_report_originating_encounter_id"), table_name="diagnostic_report"
    )
    op.drop_table("diagnostic_report")
    op.drop_index(op.f("ix_clinical_document_status"), table_name="clinical_document")
    op.drop_index(op.f("ix_clinical_document_patient_id"), table_name="clinical_document")
    op.drop_index(op.f("ix_clinical_document_encounter_id"), table_name="clinical_document")
    op.drop_index(op.f("ix_clinical_document_category"), table_name="clinical_document")
    op.drop_table("clinical_document")
    op.drop_index(op.f("ix_chart_review_status"), table_name="chart_review")
    op.drop_index(op.f("ix_chart_review_patient_id"), table_name="chart_review")
    op.drop_index(op.f("ix_chart_review_encounter_id"), table_name="chart_review")
    op.drop_table("chart_review")
    op.drop_index(op.f("ix_encounter_status"), table_name="encounter")
    op.drop_index(op.f("ix_encounter_prior_encounter_id"), table_name="encounter")
    op.drop_index(op.f("ix_encounter_patient_id"), table_name="encounter")
    op.drop_table("encounter")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(
        op.f("ix_resource_relationship_target_resource_type"), table_name="resource_relationship"
    )
    op.drop_index(
        op.f("ix_resource_relationship_target_resource_id"), table_name="resource_relationship"
    )
    op.drop_index(
        op.f("ix_resource_relationship_source_resource_type"), table_name="resource_relationship"
    )
    op.drop_index(
        op.f("ix_resource_relationship_source_resource_id"), table_name="resource_relationship"
    )
    op.drop_index(
        op.f("ix_resource_relationship_relationship_type"), table_name="resource_relationship"
    )
    op.drop_table("resource_relationship")
    op.drop_index(op.f("ix_patient_medical_record_number"), table_name="patient")
    op.drop_table("patient")
    op.drop_index(op.f("ix_clinical_provenance_resource_type"), table_name="clinical_provenance")
    op.drop_index(op.f("ix_clinical_provenance_resource_id"), table_name="clinical_provenance")
    op.drop_table("clinical_provenance")
    # ### end Alembic commands ###
